version: "3.2"
services:
  csvchecker:
    build: .
    image: sogis/csvchecker:localbuild
    environment:
      PGHOST: db
      PGDATABASE: csvchecker
      PGUSER: user
      PGPASSWORD: password
      APACHE_ACCESS_LOG_ENABLED: true
    ports:
      - "8282:8080"
  db:
    image: bitnami/postgresql:14
    environment:
      POSTGRESQL_DATABASE: csvchecker
      POSTGRESQL_USERNAME: user
      POSTGRESQL_PASSWORD: password
    volumes:
      - type: volume
        source: postgresql_data
        target: /bitnami/postgresql
      - type: bind
        source: ./db_initdb
        target: /docker-entrypoint-initdb.d
volumes:
  postgresql_data:
